# Set application name
spring.application.name=IhopArizona

# Server settings
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ihoppingArizona
spring.datasource.username=postgres
spring.datasource.password=*********

# JPA Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Auth0
auth0.audience=https://ihoppingarizona/api
auth0.issuer=https://dev-tambq5b5783bb6e2.us.auth0.com/


spring.security.oauth2.resourceserver.jwt.issuer-uri=${auth0.issuer}
spring.security.oauth2.resourceserver.jwt.audience=${auth0.audience}

spring.web.resources.static-locations=classpath:/static/,file:uploads/
# Max file size for each file
spring.servlet.multipart.max-file-size=10MB
# Max total request size (form + files)
spring.servlet.multipart.max-request-size=10MB

