# Set application name
spring.application.name=IhopArizona

# Server settings
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Auth0
auth0.audience=${AUTH0_AUDIENCE}
auth0.issuer=${AUTH0_ISSUER}


spring.security.oauth2.resourceserver.jwt.issuer-uri=${auth0.issuer}
spring.security.oauth2.resourceserver.jwt.audience=${auth0.audience}

spring.web.resources.static-locations=classpath:/static/,file:uploads/
# Max file size for each file
spring.servlet.multipart.max-file-size=10MB
# Max total request size (form + files)
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=ihoppingarizona@gmail.com
